### ISSUE TITLE
can't clone diff-gaussian-rasterization submodule 

### ISSUE THREAD

**Issue by InitialMoon** [umautobots/SAD-GS#2]
I found that you change the code of 3dgs below, deleted the viewmatrix and projmatrix, which is the params delivered to diff-gaussian-rasterization, which is the submodule of 3dgs, have you ever change this submodule's source code, I found you use this url ‘git@gitlab.eecs.umich.edu:umfordav/diff-gaussian-rasterization.git’  as repo source,  is this repo be private? Is that you forget to setting this changed submodule source code as public? Could you please open this source. Or can you tell me what have you changed?
Thanks
![image](https://github.com/user-attachments/assets/08fda6fe-0c0d-43c9-ba77-e66afdee58fb)

**Comment by Tripton** [comment]
Also having the same issue; the Git URL for the `diff-gaussian-rasterization` submodule seems to be private or possibly locked behind a firewall. This prevents me from using the approach. It would be helpful if the submodule could be shared.

**Comment by kungfrank** [comment]
@InitialMoon @Tripton Hello, sorry for the late reply. I just pushed an update and the `diff-gaussian-rasterization` should now link to a correct and public repo. Please let me know if you have any other issues!

**Comment by Tripton** [comment]
Thanks for your help, but the issue still persists. When I try to clone the repository again, I encounter the following error:
```
fatal: remote error: upload-pack: not our ref 95e01964a91773679e6d0efae6ff86e42ab124b6
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'submodules/diff-gaussian-rasterization', but it did not contain 95e01964a91773679e6d0efae6ff86e42ab124b6. Direct fetching of that commit failed.
```
Additionally, the  `submodules/diff-gaussian-rasterization` folder remains empty. Do you have any suggestions on how to resolve this?

**Comment by kungfrank** [comment]
It should be fixed now.

**Comment by Tripton** [comment]
Thanks, this worked!
